name: "02 - Workflow Events"
on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"
      timezone: Europe/Riga

jobs:
  echo:
    name: "Echo jobs"
    runs-on: ubuntu-latest
    steps:
      - name: "Show the trigger"
        run: echo "This workflow was triggered by ${{ github.event_name }}"