name: "09 - Using Functions"
on:
  pull_request:
  workflow_dispatch:
env:
  WORKFLOW_VAR: "I am a workflow env var"
  OVERWRITTEN: "I will be overwritten"
  UNDEFINED_VAR_WITH_DEFAULT: ${{ vars.UNDEFINED_VAR || 'default value' }}
jobs:
  echo1 :
    name: "Echo"
    runs-on: ubuntu-latest
    steps:
      - name: "Print PR title"
        run: |
            echo "PR title: ${{ github.event.pull_request.title || 'No title specified or workflow not triggered by a pull_request event' }}"
      - name: "Print PR labels"
        run: |
            echo "Pull request labels (string): ${{ join(github.event.pull_request.labels, ',' ) || 'No labels attached' }}"
            echo "Pull request labels (JSON): ${{ github.event.pull_request.labels && toJson(github.event.pull_request.labels) || 'No labels attached' }}"
      - name: "Sleep for 20 seconds"
        run: sleep 20
      - name: "Failing step"
        run: exit 1
      - name: "I will be skipped"
        if: ${{ success() }}
        run: |
          echo "I will print if previous steps succeed."
      - name: "I will execute"
        if: ${{ failure() }}
        run: |
          echo "I will print if any previous step fails."
      - name: "I will execute"
        if: ${{ !cancelled() }}
        run: |
          echo "I will always print, except when the workflow is cancelled."
      - name: "Bug step"
        if: ${{ failure() && !cancelled() && contains(github.event.pull_request.title, 'fix') }}
        run: |
          echo "I am a bug fix"
      - name: "I will execute when cancelled"
        if: cancelled()
        run: |
          echo "Workflow was cancelled"